##
# This file is part of the Akelia package.
#
# (c) Romain Monceau
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

connector:
    jobs:
        thelia_product_export:
            title: fitn_thelia.jobs.product.export.title
            type: export
            steps:
                export:
                    title: fitn_thelia.jobs.product.export.title
                    services:
                        reader:    pim_base_connector.reader.dummy
                        processor: pim_base_connector.processor.dummy
                        writer:    pim_base_connector.writer.dummy
